version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '12.18.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test