version: 2
jobs:
  build:
    environment: 
      IMAGE_NAME: jhlcandido/bossabox-desafio-backend
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters: 
            branches:
              ignore: master
